// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7MOQfsIvg59VUh_ufJQf8OSgUk0oifs0',
    appId: '1:191424702957:web:f2cc1ec2eac9503f4c5fe4',
    messagingSenderId: '191424702957',
    projectId: 'siren-182b8',
    authDomain: 'siren-182b8.firebaseapp.com',
    storageBucket: 'siren-182b8.firebasestorage.app',
    measurementId: 'G-65XXHT5LE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKePKzHDwjduqGYVBt97cocnQXz1K78Ns',
    appId: '1:191424702957:android:bb2adcba8a08049f4c5fe4',
    messagingSenderId: '191424702957',
    projectId: 'siren-182b8',
    storageBucket: 'siren-182b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP-C0oFkqmpDVqCjc1a8kAcGAMQbs9q4U',
    appId: '1:191424702957:ios:8bb7fea6f66677494c5fe4',
    messagingSenderId: '191424702957',
    projectId: 'siren-182b8',
    storageBucket: 'siren-182b8.firebasestorage.app',
    iosBundleId: 'com.example.flutterSiren',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP-C0oFkqmpDVqCjc1a8kAcGAMQbs9q4U',
    appId: '1:191424702957:ios:8bb7fea6f66677494c5fe4',
    messagingSenderId: '191424702957',
    projectId: 'siren-182b8',
    storageBucket: 'siren-182b8.firebasestorage.app',
    iosBundleId: 'com.example.flutterSiren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7MOQfsIvg59VUh_ufJQf8OSgUk0oifs0',
    appId: '1:191424702957:web:9784863e235b0eb44c5fe4',
    messagingSenderId: '191424702957',
    projectId: 'siren-182b8',
    authDomain: 'siren-182b8.firebaseapp.com',
    storageBucket: 'siren-182b8.firebasestorage.app',
    measurementId: 'G-WZCE55F7VD',
  );

}